config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'oven_logs#index'
  resources :oven_logs

end

app/models/oven_log.rb
class OvenLog < ActiveRecord::Base
  belongs_to :user

  validates :customer, presence: :true
  validates :work_order, presence: :true
  validates :purchase_order, presence: :true
  validates :operator, presence: :true

  validates_presence_of :stress_asset, :if => :stress_in
  validates_presence_of :her_asset, :if => :her_in
  validates_presence_of :stress_in, :stress_out, :her_out, :her_in, :her_asset, :stress_asset, allow_blank: true

  validate :stress_in_must_be_before_stress_out, :if => :stress_in
  validate :her_in_must_be_before_her_out, :if => :her_in



  def stress_in_must_be_before_stress_out
    if stress_in.present?
      errors.add(:stress_in, "must be before Stress out") unless
      (stress_in < stress_out)
    end
  end

  def her_in_must_be_before_her_out
    if her_in.present?
      errors.add(:her_in, "must be before HER out") unless
      (her_in < her_out)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :oven_logs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/oven_logs_controller.rb
class OvenLogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @oven_log = OvenLog.all
    @oven_logs_grid = initialize_grid(OvenLog,
    order: 'oven_logs.customer',
    order_direction: 'asc'
    )
  end

  def new
    @oven_log = OvenLog.new
  end

  def create
    @oven_log = current_user.oven_logs.create(oven_log_params)
    if @oven_log.save
      flash[:success] = 'New log created!'
      redirect_to oven_logs_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @oven_log = OvenLog.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        pdf = LogPdf.new(@oven_log)
        send_data pdf.render, filename: "#{@oven_log.customer} #{@oven_log.work_order}.pdf",
                                type: "application/pdf",
                                disposition: "inline"
      end
    end
  end
  def edit
    @oven_log = OvenLog.find(params[:id])
  end

  def update
    @oven_log = OvenLog.find(params[:id])
    @oven_log.update_attributes(oven_log_params)
    if @oven_log.valid?
      redirect_to oven_logs_path
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @oven_log = OvenLog.find(params[:id])
    @oven_log.destroy
    redirect_to oven_logs_path
  end
end

private
def oven_log_params
  params.require(:oven_log).permit(:customer, :work_order, :purchase_order, :stress_in, :stress_out,  :stress_asset, :her_in, :her_out, :her_asset, :operator)

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Date
# ----------------------------
Date::DATE_FORMATS[:default] = 'MM/DD/YYYY'

# DateTime / Time
# ----------------------------
Time::DATE_FORMATS[:default] = "%m/%d/%y %I:%M %p"
end

app/helpers/oven_logs_helper.rb
module OvenLogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ovenlogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Oven Logger', root_path, class: 'navbar-brand' %>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

        <li>
          <%= link_to 'New Log', new_oven_log_path, class: 'nav navbar-nav' %>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>


  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/oven_logs/edit.html.erb
<br  />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Edit Oven Log Entry</h1>
  <br  />
  <%= simple_form_for @oven_log do |f| %>

  <table class="table">
    <td><%= f.input :customer%></td>
    <td><%= f.input :work_order, label: 'Work Order'%></td>
    <td><%= f.input :purchase_order, label: 'Purchase Order'%></td>
    <td><%= f.input :operator, label: 'Operator' %></td>
  </table>

  <table class="table">
    <td><%= f.input :stress_in, :include_blank => true, as: :datetime_picker, label: 'Stress in (DD/MM/YY)' %></td>

    <td><%= f.input :stress_out, :include_blank => true, label: 'Stress out (DD/MM/YY)', as: :datetime_picker  %></td>
    <td><%= f.input :stress_asset, :include_blank => true, label: 'Asset'  %></td>
    <td><%= f.input :her_in, :include_blank => true, label: 'HER in (DD/MM/YY)', as: :datetime_picker %></td>
    <td><%= f.input :her_out, :include_blank => true, label: 'HER out (DD/MM/YY)', as: :datetime_picker %></td>
    <td><%= f.input :her_asset, label: 'Asset' %></td>
  </table>
  <table>
  </div>
  <div class="twobuttons">

    <%= f.submit "Submit", class: 'btn btn-info'  %>
      <%= link_to 'Delete Record', oven_log_path(@oven_log), method: :delete, :data => { :confirm => 'Are you sure you want to delete this record?' }, :class => 'btn btn-danger' %>
    </div>
  <% end %>
</div>

app/views/oven_logs/index.html.erb
<br />
<div class="booyah-box">
  <%# %>
  <%= grid(@oven_logs_grid, upper_pagination_panel: true, ) do |g|

    g.column name: 'Customer', attribute: 'customer' do |oven_log|
      oven_log.customer
    end

    g.column name: 'Work Order', attribute: 'work_order' do |oven_log|
      oven_log.work_order
    end

    g.column name: 'Purchase Order', attribute: 'purchase_order' do |oven_log|
      oven_log.purchase_order
    end

    g.column name: 'Stress in', attribute: 'stress_in', filter_type: :bootstrap_datepicker do |oven_log|
      oven_log.stress_in
    end

    g.column name: 'Stress out', attribute: 'stress_out', filter_type: :bootstrap_datepicker do |oven_log|
      oven_log.stress_out
    end

    g.column name: 'Asset', attribute: 'stress_asset', filter_type: :false do |oven_log|
      oven_log.stress_asset
    end

    g.column name: 'HER in', attribute: 'her_in', filter_type: :bootstrap_datepicker do |oven_log|
      oven_log.her_in
    end


    g.column name: 'HER out', attribute: 'her_out', filter_type: :bootstrap_datepicker do |oven_log|
      oven_log.her_out
    end

    g.column name: 'Asset', attribute: 'her_asset', filter_type: :false do |oven_log|
      oven_log.her_asset
    end

    g.column name: 'Operator' do |oven_log|
      oven_log.operator
    end

    g.column name: 'Edit?' do |oven_log|
      link_to('Modify', edit_oven_log_path(oven_log))
    end

    g.column name: "View Log" do |oven_log|
      link_to('View', oven_log_path(oven_log))
    end


  end %>
</div>

app/views/oven_logs/new.html.erb
<br  />

<div class="booyah-box col-xs-12">
  <h1 class="text-center">Add a New Oven Log Entry</h1>
  <br  />
  <%= simple_form_for @oven_log, url: oven_logs_path do |f| %>

  <table class="table new-log text-center">
    <td><%= f.input :customer%></td>
    <td><%= f.input :work_order, label: 'Work Order'%></td>
    <td><%= f.input :purchase_order, label: 'Purchase Order'%></td>
    <td><%= f.input :operator, label: 'Operator'                                               %></td>
  </table>

  <table class="table new-log text-center">
    <td><%= f.input :stress_in, :include_blank => true, as: :datetime_picker, label: 'Stress in (DD/MM/YY)' %></td>

    <td><%= f.input :stress_out, :include_blank => true, label: 'Stress out        (DD/MM/YY)', as: :datetime_picker          %></td>
    <td><%= f.input :stress_asset, :include_blank => true, label: 'Stress Asset'               %></td>
    <td><%= f.input :her_in, :include_blank => true, label: 'HER in   (DD/MM/YY)', as: :datetime_picker %></td>
    <td><%= f.input :her_out, :include_blank => true, label: 'HER out   (DD/MM/YY)', as: :datetime_picker %></td>
    <td><%= f.input :her_asset, label: 'HER Asset'          %></td>
  </table>
  <table>

  <table>
    <%= f.submit "Submit", class: 'btn btn-info'                  %>
    </table

    <% end %>
  </table>
</div>

app/views/oven_logs/show.html.erb
<div class="booyah-box">
  <table class="table a">
    <tr class="active">
      <td>Customer: <%= @oven_log.customer %></td>
      <td>Work Order: <%= @oven_log.work_order %></td>
      <td>Purchase Order: <%= @oven_log.purchase_order %></td>
    </tr>

    <tr class="default">
      <td>Stress in: <%= @oven_log.stress_in %></td>
      <td>Stress out: <%= @oven_log.stress_out %></td>
      <td>Asset: <%= @oven_log.stress_asset %></td>
    </tr>
    <tr class="active">
      <td>HER in: <%= @oven_log.her_in %></td>
      <td>HER out: <%= @oven_log.her_out %></td>
      <td>Asset: <%= @oven_log.her_asset %></td>
    </tr>
    <tr class="default">
      <td>Operator: <%= @oven_log.operator %></td>
    </tr>
  </table>

<p><%= link_to "Print Log (PDF)", oven_log_path(@oven_log, format: "pdf")%></p>
</div>